import { iPlanta } from "@/types/index";

export const base_plantas: iPlanta[] = [
  {
    id: 1,
    nome: "Tomate",
    espacamento_cm: 50,
    ciclo_dias: 90,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Alto",
    consorcio: ["Manjericão", "Cenoura", "Alho", "Calêndula"],
    descricao_embrapa:
      "O tomateiro exige solos bem drenados e ricos em matéria orgânica. Requer tutoramento e podas de brotos ladrões para melhor produtividade.",
  },
  {
    id: 2,
    nome: "Alface",
    espacamento_cm: 25,
    ciclo_dias: 45,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Rabanete", "Cenoura", "Cebolinha"],
    descricao_embrapa:
      "Cultura de ciclo curto, prefere climas amenos. O solo deve ser mantido úmido, mas sem encharcamento para evitar podridão radicular.",
  },
  {
    id: 3,
    nome: "Cenoura",
    espacamento_cm: 10,
    ciclo_dias: 100,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Baixo",
    consorcio: ["Tomate", "Alface", "Ervilha"],
    descricao_embrapa:
      "Exige solos profundos, leves e sem pedregulhos para o desenvolvimento reto da raiz. Sensível ao excesso de nitrogênio.",
  },
  {
    id: 4,
    nome: "Manjericão",
    espacamento_cm: 30,
    ciclo_dias: 60,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Médio",
    consorcio: ["Tomate", "Pimentão", "Abobrinha"],
    descricao_embrapa:
      "Planta aromática que auxilia no controle biológico de pragas. Prefere calor e não tolera geadas.",
  },
  {
    id: 5,
    nome: "Pimentão",
    espacamento_cm: 40,
    ciclo_dias: 110,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Alto",
    consorcio: ["Manjericão", "Cebola", "Cenoura"],
    descricao_embrapa:
      "Exigente em temperatura e fertilidade. Requer fornecimento constante de cálcio para evitar a podridão apical.",
  },
  {
    id: 6,
    nome: "Abobrinha",
    espacamento_cm: 100,
    ciclo_dias: 50,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Milho", "Feijão", "Capuchinha"],
    descricao_embrapa:
      "Crescimento rápido e rasteiro. Necessita de polinização por abelhas para a formação dos frutos.",
  },
  {
    id: 7,
    nome: "Milho",
    espacamento_cm: 20,
    ciclo_dias: 120,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Emergente",
    consorcio: ["Feijão", "Abóbora", "Pepino"],
    descricao_embrapa:
      "Planta de ciclo anual, muito exigente em nitrogênio. Serve como suporte natural para trepadeiras em sistemas de milpa.",
  },
  {
    id: 8,
    nome: "Feijão",
    espacamento_cm: 10,
    ciclo_dias: 80,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Médio",
    consorcio: ["Milho", "Couve", "Batata"],
    descricao_embrapa:
      "Leguminosa que realiza fixação biológica de nitrogênio no solo, beneficiando as plantas vizinhas.",
  },
  {
    id: 9,
    nome: "Couve",
    espacamento_cm: 60,
    ciclo_dias: 70,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Médio",
    consorcio: ["Alecrim", "Sálvia", "Hortelã"],
    descricao_embrapa:
      "Planta perene em climas favoráveis. Exige alta disponibilidade de nitrogênio e matéria orgânica.",
  },
  {
    id: 10,
    nome: "Rabanete",
    espacamento_cm: 5,
    ciclo_dias: 25,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Alface", "Ervilha", "Espinafre"],
    descricao_embrapa:
      "Uma das culturas mais rápidas para colheita. Ideal para aproveitar espaços entre plantas de ciclo longo.",
  },
  {
    id: 11,
    nome: "Berinjela",
    espacamento_cm: 60,
    ciclo_dias: 120,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Alto",
    consorcio: ["Feijão", "Pimentão", "Tomilho"],
    descricao_embrapa:
      "Prefere climas quentes. O fruto deve ser colhido antes de perder o brilho para garantir a qualidade culinária.",
  },
  {
    id: 12,
    nome: "Beterraba",
    espacamento_cm: 10,
    ciclo_dias: 70,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Baixo",
    consorcio: ["Cebola", "Alface", "Repolho"],
    descricao_embrapa:
      "Desenvolve-se melhor em solos leves. As folhas também são comestíveis e ricas em nutrientes.",
  },
  {
    id: 13,
    nome: "Cebola",
    espacamento_cm: 10,
    ciclo_dias: 150,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Baixo",
    consorcio: ["Beterraba", "Tomate", "Morango"],
    descricao_embrapa:
      "Cultura sensível ao fotoperíodo para a formação do bulbo. Exige solo bem drenado para evitar fungos.",
  },
  {
    id: 14,
    nome: "Alho",
    espacamento_cm: 10,
    ciclo_dias: 180,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Baixo",
    consorcio: ["Tomate", "Pepino", "Rosa"],
    descricao_embrapa:
      "Exige longo período de cultivo. Atua como repelente natural para diversas pragas de jardim.",
  },
  {
    id: 15,
    nome: "Salsa",
    espacamento_cm: 15,
    ciclo_dias: 70,
    luz: "Meia-sombra",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Aspargos", "Tomate", "Cebolinha"],
    descricao_embrapa:
      "Bienal, mas cultivada como anual. Prefere solos ricos em húmus e locais com sombra parcial nas horas quentes.",
  },
  {
    id: 16,
    nome: "Cebolinha",
    espacamento_cm: 10,
    ciclo_dias: 60,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Alface", "Cenoura", "Tomate", "Salsa"],
    descricao_embrapa:
      "Planta rústica que se desenvolve bem em solos ricos em matéria orgânica. O corte deve ser feito preservando o pseudocaule para rebrota.",
  },
  {
    id: 17,
    nome: "Ervilha",
    espacamento_cm: 20,
    ciclo_dias: 70,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Médio",
    consorcio: ["Cenoura", "Rabanete", "Milho"],
    descricao_embrapa:
      "Leguminosa de clima ameno. Ajuda na fixação de nitrogênio e, se for de variedade trepadeira, necessita de suportes ou tutores.",
  },
  {
    id: 18,
    nome: "Pepino",
    espacamento_cm: 50,
    ciclo_dias: 60,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Milho", "Girassol", "Alho", "Feijão"],
    descricao_embrapa:
      "Planta rasteira ou trepadeira de crescimento rápido. Exige polinização cruzada e solos com boa drenagem.",
  },
  {
    id: 19,
    nome: "Alecrim",
    espacamento_cm: 80,
    ciclo_dias: 365,
    luz: "Pleno",
    rega: "Baixa",
    estrato: "Médio",
    consorcio: ["Sálvia", "Couve", "Cenoura"],
    descricao_embrapa:
      "Arbusto perene e resistente. Prefere solos arenosos e não tolera o encharcamento das raízes.",
  },
  {
    id: 20,
    nome: "Capuchinha",
    espacamento_cm: 40,
    ciclo_dias: 50,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Baixo",
    consorcio: ["Abobrinha", "Tomate", "Pepino"],
    descricao_embrapa:
      "Planta comestível (PANC) que atua como planta-armadilha para pulgões, protegendo as culturas principais do jardim.",
  },
  {
    id: 21,
    nome: "Sálvia",
    espacamento_cm: 40,
    ciclo_dias: 120,
    luz: "Pleno",
    rega: "Baixa",
    estrato: "Médio",
    consorcio: ["Alecrim", "Couve", "Cenoura"],
    descricao_embrapa:
      "Planta medicinal e aromática que prefere solos bem drenados. Ajuda a repelir a mosca-da-couve.",
  },
  {
    id: 22,
    nome: "Hortelã",
    espacamento_cm: 30,
    ciclo_dias: 90,
    luz: "Meia-sombra",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Couve", "Tomate"],
    descricao_embrapa:
      "Planta invasiva que deve ser controlada. Seu odor forte confunde pragas que atacam as brássicas.",
  },
  {
    id: 23,
    nome: "Espinafre",
    espacamento_cm: 25,
    ciclo_dias: 60,
    luz: "Meia-sombra",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Rabanete", "Morango", "Couve-flor"],
    descricao_embrapa:
      "Rico em ferro e nitratos, prefere climas frescos. O excesso de calor pode estimular o florescimento precoce.",
  },
  {
    id: 24,
    nome: "Calêndula",
    espacamento_cm: 30,
    ciclo_dias: 60,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Baixo",
    consorcio: ["Tomate", "Batata", "Feijão"],
    descricao_embrapa:
      "Flor comestível que auxilia no manejo de nematoides no solo e atrai polinizadores e insetos benéficos.",
  },
  {
    id: 25,
    nome: "Batata",
    espacamento_cm: 30,
    ciclo_dias: 110,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Baixo",
    consorcio: ["Milho", "Feijão", "Repolho"],
    descricao_embrapa:
      "Exige amontoa (cobrir a base com terra) para proteger os tubérculos da luz. Sensível a requeima em períodos húmidos.",
  },
  {
    id: 26,
    nome: "Morango",
    espacamento_cm: 30,
    ciclo_dias: 120,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Cebola", "Alface", "Espinafre"],
    descricao_embrapa:
      "Exige solos bem drenados e ricos em matéria orgânica. O uso de mulching (cobertura morta) é essencial para evitar o contato dos frutos com o solo.",
  },
  {
    id: 27,
    nome: "Rosa",
    espacamento_cm: 100,
    ciclo_dias: 180,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Alto",
    consorcio: ["Alho", "Cebola", "Sálvia"],
    descricao_embrapa:
      "Utilizada em bordaduras de hortas para atrair polinizadores. O plantio com alho ajuda a repelir pulgões que atacam as pétalas.",
  },
  {
    id: 28,
    nome: "Aspargos",
    espacamento_cm: 40,
    ciclo_dias: 730, // Planta perene, colheita viável após o 2º ano
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Médio",
    consorcio: ["Salsa", "Tomate", "Manjericão"],
    descricao_embrapa:
      "Cultura perene que exige paciência no estabelecimento. O sistema radicular é profundo e se beneficia da vizinhança com o tomate para repelir o besouro-do-aspargo.",
  },
  {
    id: 29,
    nome: "Repolho",
    espacamento_cm: 50,
    ciclo_dias: 90,
    luz: "Pleno",
    rega: "Frequente",
    estrato: "Baixo",
    consorcio: ["Beterraba", "Alecrim", "Sálvia"],
    descricao_embrapa:
      "Brássica que exige muito nitrogênio. O consórcio com ervas aromáticas é fundamental para confundir a traça-das-crucíferas.",
  },
  {
    id: 30,
    nome: "Tomilho",
    espacamento_cm: 20,
    ciclo_dias: 90,
    luz: "Pleno",
    rega: "Baixa",
    estrato: "Baixo",
    consorcio: ["Berinjela", "Repolho", "Batata"],
    descricao_embrapa:
      "Planta rústica que prefere solos secos e pobres. Seu aroma ajuda a repelir pragas que atacam solanáceas como a berinjela.",
  },
  {
    id: 31,
    nome: "Abóbora",
    espacamento_cm: 200,
    ciclo_dias: 120,
    luz: "Pleno",
    rega: "Moderada",
    estrato: "Baixo",
    consorcio: ["Milho", "Feijão"],
    descricao_embrapa:
      "Componente clássico da Milpa. Suas folhas largas sombreiam o solo, mantendo a umidade e suprimindo ervas espontâneas.",
  },
  {
        id: 32,
        nome: "Girassol",
        espacamento_cm: 50,
        ciclo_dias: 90,
        luz: "Pleno",
        rega: "Moderada",
        estrato: "Emergente",
        consorcio: ["Pepino", "Feijão", "Milho"],
        descricao_embrapa: "Planta de crescimento vertical rápido que serve como quebra-vento e suporte para trepadeiras. Atrai polinizadores e ajuda a extrair metais pesados do solo."
    },
    {
        id: 33,
        nome: "Couve-flor",
        espacamento_cm: 60,
        ciclo_dias: 100,
        luz: "Pleno",
        rega: "Frequente",
        estrato: "Baixo",
        consorcio: ["Espinafre", "Alecrim", "Sálvia", "Aipo"],
        descricao_embrapa: "Exigente em boro e molibdênio. Requer proteção da inflorescência contra o sol direto em algumas variedades para manter a coloração branca."
    },

];
